(##supply-module all)

(declare
  (standard-bindings)
  (extended-bindings))

(##namespace ("all#"))
(##include "~~lib/gambit#.scm")

(include "header.scm")
(include "kernel.scm")
(include "core.scm")
(include "syntax.scm")
(include "exception.scm")
(include "class.scm")
(include "sequence.scm")
(include "object.scm")
(include "jazz.scm")
(include "math.scm")
(include "uuid.scm")
(include "version.scm")
(include "settings.scm")
(include "network.scm")
(include "listener.scm")
(include "ior.scm")
(include "proxy.scm")
(include "register.scm")
(include "transmission.scm")
(include "presence.scm")
(include "remotable.scm")
(include "stubs.scm")
(include "debuggee.scm")
(include "process.scm")
(include "thread.scm")
(include "restart.scm")
(include "stop.scm")
(include "frame.scm")
(include "evaluate.scm")
(include "inspector.scm")
