(##supply-module all)

(declare
  (standard-bindings)
  (extended-bindings))

(##namespace ("all#"))
(##include "~~lib/gambit#.scm")

(include "lib/header.scm")
(include "lib/kernel.scm")
(include "lib/core.scm")
(include "lib/syntax.scm")
(include "lib/exception.scm")
(include "lib/class.scm")
(include "lib/sequence.scm")
(include "lib/object.scm")
(include "lib/jazz.scm")
(include "lib/math.scm")
(include "lib/uuid.scm")
(include "lib/version.scm")
(include "lib/settings.scm")
(include "lib/network.scm")
(include "lib/listener.scm")
(include "lib/ior.scm")
(include "lib/proxy.scm")
(include "lib/register.scm")
(include "lib/transmission.scm")
(include "lib/presence.scm")
(include "lib/remotable.scm")
(include "lib/stubs.scm")
(include "lib/debuggee.scm")
(include "lib/process.scm")
(include "lib/thread.scm")
(include "lib/restart.scm")
(include "lib/stop.scm")
(include "lib/frame.scm")
(include "lib/evaluate.scm")
(include "lib/inspector.scm")
